# Generated by Django 5.2.1 on 2025-05-23 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_alter_child_height_alter_child_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('hour_init', models.TimeField(verbose_name='hora')),
                ('hour_end', models.TimeField(verbose_name='hora')),
                ('description', models.CharField(max_length=50)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.child')),
            ],
        ),
    ]
