# Generated by Django 5.2.1 on 2025-05-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('dashboard', '0002_alter_child_height_alter_child_weight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='Evento',
        ),
    ]
