# Generated by Django 5.2.3 on 2025-06-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_rename_agenda_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20),
        ),
    ]
