# Generated by Django 5.2.1 on 2025-05-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='child',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
