# Generated by Django 5.2.3 on 2025-06-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_child_height_alter_child_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20),
        ),
    ]
