# Generated by Django 5.2.1 on 2025-05-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SEG', 'Segunda'), ('TER', 'Terça'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], help_text='Dia da semana para a rotina.', max_length=3, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='routine',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='routine',
            name='days_of_week',
            field=models.ManyToManyField(help_text='Dias da semana em que a rotina se aplica.', related_name='routines', to='rotina.weekday'),
        ),
    ]
