# Generated by Django 5.2.1 on 2025-05-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0002_weekday_remove_routine_days_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekday',
            name='day',
            field=models.CharField(choices=[('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday'), ('1', 'Sunday')], help_text='Dia da semana para a rotina.', max_length=3, unique=True),
        ),
    ]
