# Generated by Django 5.2.1 on 2025-05-29 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0003_alter_weekday_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='end_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='start_day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
