# Generated by Django 5.2.1 on 2025-05-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0004_routine_end_day_routine_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekday',
            name='day',
            field=models.CharField(choices=[('1', 'SEG'), ('2', 'TER'), ('3', 'QUA'), ('4', 'QUI'), ('5', 'SEX'), ('6', 'SAB'), ('7', 'DOM')], help_text='Dia da semana para a rotina.', max_length=3, unique=True),
        ),
    ]
