# Generated by Django 5.2.1 on 2025-05-30 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_child_height_alter_child_weight'),
        ('rotina', '0005_alter_weekday_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='dashboard.child'),
            preserve_default=False,
        ),
    ]
