# Generated by Django 5.2.1 on 2025-05-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0006_routine_child'),
    ]

    operations = [
    ]
