# Generated by Django 5.2.3 on 2025-06-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0007_fix_child_default'),
    ]

    operations = [
    ]
