# Generated by Django 5.2.3 on 2025-06-11 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_health_status_school_status'),
        ('rotina', '0008_auto_20250611_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='routine',
            name='child',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='dashboard.child'),
            preserve_default=False,
        ),
    ]
